version: '3.8'

services:
  zoo:
    image: zookeeper
    ports:
      - 2181:2181
  zk-web:
    image: noteax/zk-web-docker
    environment:
      ZKWEB_DEFAULT_NODE: zoo
    ports:
      - 8080:8080
    
